export const LOGIN_SET_USERNAME = 'LOGIN_SET_USERNAME';
export const LOGIN_SET_PASSWORD = 'LOGIN_SET_PASSWORD';
export const LOGIN_SET_ERROR    = 'LOGIN_SET_ERROR';
export const LOGIN_CLEAR = 'LOGIN_CLEAR';