export const REGISTRATION_SET_USERNAME = 'REGISTRATION_SET_USERNAME';
export const REGISTRATION_SET_PASSWORD = 'REGISTRATION_SET_PASSWORD';
export const REGISTRATION_SET_ERROR = 'REGISTRATION_SET_ERROR';
export const REGISTRATION_SET_REGISTERED  = 'REGISTRATION_SET_REGISTERED';
export const REGISTRATION_CLEAR = 'REGISTRATION_CLEAR';